server:
  port: 9007
spring:
  application:
    name: tensquare-search # 指定服务器
  data:
    elasticsearch:
      cluster-nodes: 192.168.0.104:9300
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/tensquare_gathering?serverTimezone=UTC&characterEncoding=utf-8
#    username: root
#    password: root
#  jpa:
#    show-sql: true
#    database: mysql
